export const dataProcessing = {
  badge: "Customer Compliance",
  title: "Data Processing",
  description:
    "This page explains, in plain language, how Avenro currently processes public widget data and where that data flows through the product. It is intended for signed-in customers and compliance reviews.",
  lastUpdated: "Last updated: March 23, 2026",
  backToSettings: "Back to settings",
  subprocessors: "Subprocessors",
  publicPrivacyPolicy: "Public privacy policy",
  sections: [
    {
      title: "Controller and processor roles",
      body: [
        "When a website visitor interacts with an Avenro-powered widget, the website owner is usually the controller for the business purpose behind that conversation.",
        "Avenro operates the infrastructure layer that stores widget configuration, chat runtime data, lead captures, and analytics support data. In that context Avenro acts as a processor or subprocessor, depending on the customer relationship.",
      ],
    },
    {
      title: "What public widgets may collect",
      body: [
        "Public widgets may process chat messages, selected agent context, lead form submissions, contact details, booking details, session identifiers, page URL, referrer, origin, timestamps, and session activity metadata.",
        "If a workspace has connected Gmail or Google Calendar tools, the runtime may also send the minimum action payloads needed to carry out email or booking actions requested through the configured agent.",
      ],
    },
    {
      title: "How the runtime works",
      body: [
        "Widget visitors talk to an Avenro runtime that stores the conversation in Supabase and sends model requests through OpenRouter. If the agent is configured with external tools, those actions are executed through Composio.",
        "Analytics and inbox views are built from widget session, message, and lead records generated by those public conversations.",
      ],
    },
    {
      title: "Retention",
      body: [
        "Avenro currently applies a default 180 day retention policy for widget sessions, widget messages, widget leads, and widget session activity metadata.",
        "Imported knowledge sources and stored knowledge files are retained until the workspace deletes them manually.",
      ],
    },
    {
      title: "Privacy requests",
      body: [
        "If your data was collected through a customer widget, the fastest route is normally to contact the website owner directly first.",
        "Avenro also supports platform-level privacy handling for public widget data through internal owner-only export and deletion workflows.",
      ],
    },
  ],
};
