import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Data Processing | Agentergroup",
  description:
    "Public explanation of how Agentergroup processes public widget, lead, and runtime data.",
};

const sections = [
  {
    title: "Controller and processor roles",
    body: [
      "When a website visitor interacts with an Agentergroup-powered widget, the website owner is usually the controller for the business purpose behind that conversation.",
      "Agentergroup operates the infrastructure layer that stores widget configuration, chat runtime data, lead captures, and analytics support data. In that context Agentergroup acts as a processor or subprocessor, depending on the customer relationship.",
    ],
  },
  {
    title: "What public widgets may collect",
    body: [
      "Public widgets may process chat messages, selected agent context, lead form submissions, contact details, booking details, session identifiers, page URL, referrer, origin, timestamps, and session activity metadata.",
      "If a workspace has connected Gmail or Google Calendar tools, the runtime may also send the minimum action payloads needed to carry out email or booking actions requested through the configured agent.",
    ],
  },
  {
    title: "How the runtime works",
    body: [
      "Widget visitors talk to an Agentergroup runtime that stores the conversation in Supabase and sends model requests through OpenRouter. If the agent is configured with external tools, those actions are executed through Composio.",
      "Analytics and inbox views are built from widget session, message, and lead records generated by those public conversations.",
    ],
  },
  {
    title: "Retention",
    body: [
      "Agentergroup currently applies a default 180 day retention policy for widget sessions, widget messages, widget leads, and widget session activity metadata.",
      "Imported knowledge sources and stored knowledge files are retained until the workspace deletes them manually.",
    ],
  },
  {
    title: "Privacy requests",
    body: [
      "If your data was collected through a customer widget, the fastest route is normally to contact the website owner directly first.",
      "Agentergroup also supports platform-level privacy handling for public widget data through internal owner-only export and deletion workflows.",
    ],
  },
];

export default function DataProcessingPage() {
  return (
    <main className="min-h-screen bg-[linear-gradient(180deg,#f7f8fb_0%,#eef2f6_100%)] text-on-surface">
      <div className="mx-auto flex w-full max-w-4xl flex-col gap-10 px-6 py-16 sm:px-8 sm:py-20">
        <section className="rounded-[28px] border border-outline-variant/20 bg-white/90 p-8 shadow-sm shadow-slate-200/60 sm:p-10">
          <p className="text-xs font-semibold uppercase tracking-[0.24em] text-on-surface-variant">
            Public Legal Page
          </p>
          <h1 className="mt-4 text-4xl font-bold tracking-tight text-on-surface sm:text-5xl">
            Data Processing
          </h1>
          <p className="mt-4 max-w-3xl text-sm leading-7 text-on-surface-variant sm:text-base">
            This page explains, in plain language, how Agentergroup currently processes public
            widget data and where that data flows through the product.
          </p>
          <div className="mt-6 flex flex-wrap items-center gap-3 text-xs text-on-surface-variant sm:text-sm">
            <span className="rounded-full border border-outline-variant/25 bg-surface px-3 py-1.5">
              Last updated: March 23, 2026
            </span>
            <Link
              href="/privacy-policy"
              className="rounded-full border border-outline-variant/25 bg-surface px-3 py-1.5 transition-colors hover:bg-surface-container"
            >
              Privacy policy
            </Link>
            <Link
              href="/subprocessors"
              className="rounded-full border border-outline-variant/25 bg-surface px-3 py-1.5 transition-colors hover:bg-surface-container"
            >
              Subprocessors
            </Link>
          </div>
        </section>

        <div className="grid gap-4">
          {sections.map((section) => (
            <section
              key={section.title}
              className="rounded-[24px] border border-outline-variant/15 bg-white/85 p-6 shadow-sm shadow-slate-200/40 sm:p-7"
            >
              <h2 className="text-xl font-semibold tracking-tight text-on-surface">
                {section.title}
              </h2>
              <div className="mt-3 space-y-3 text-sm leading-7 text-on-surface-variant sm:text-[15px]">
                {section.body.map((paragraph) => (
                  <p key={paragraph}>{paragraph}</p>
                ))}
              </div>
            </section>
          ))}
        </div>
      </div>
    </main>
  );
}
